# Terminal & Colors
set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"
set -g escape-time 0

# Mouse
set -g mouse on

# General
set -g allow-passthrough on
set -g visual-bell off
set -g bell-action none
set -g history-limit 100000
set -s set-clipboard on
set -g focus-events on

# Window title
set -g set-titles on
set -g set-titles-string "#{pane_title} [#h]"

# Prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix

